### PR TITLE
Ignore .prob on bilingual modules

### LINKED ISSUE #42: Ignore .prob on bilingual modules
Prob files have to exist, but they are on the monolingual modules. They shouldn't be versioned on the bilingual ones.

Example:
* `apertium-cat` -> `apertium-cat.cat.prob` **added** to GIT
* `apertium-spa` -> `apertium-cat.spa.prob` **added** to GIT
* `apertium-spa-cat` -> `cat-spa.prob` and `spa-cat.prob` **ignored** in GIT

### PR DESCRIPTION
**Pull request by Sheogorath2**
Fix #42

### CODE REVIEW

**Comment by sushain97** [comment]
This change would ignore them for all modules. We want to only do so for pairs.

**Comment by xavivars** [comment]
It actually wouldn't (at least in most cases). In most monolinguals, the name of the file is cat.prob, while it becomes cat-spa.prob in the bilingual.

However, I'd still prefer a *.prob on the bilingual and nothing in the monolingual, as the previous paragraph is a convention I'm not sure 100% modules follow.

**Comment by sushain97** [comment]
oooh, I must have misread the diff, my bad.

In that case, I think this gitignore is fine since all we have to do is work with the conventions used within apertium-init, right?

**Comment by xavivars** [comment]
And it does...

https://github.com/apertium/apertium-init/blob/47b9de44eca41da99feef2436279c85c1cfb12d0/bilingual-module/Makefile.am#L137

**Pull request merged**
