### PR TITLE
Add Options for New Modules

### PR DESCRIPTION
**Pull request by mr-martian**
This PR adds options for the new modules from GSoC:
- Apertium-anaphora `--with-anaphora`
- Apertium-recursive `--transfer=rtx` (as opposed to t*x, which is `--transfer=chunk` or nothing)

### CODE REVIEW

**Comment by sushain97** [comment]
Nice PR. Would prefer to block until builds pass.

Also, is it possible to have smaller example files?

**Comment by mr-martian** [comment]
> Nice PR. Would prefer to block until builds pass.

I waited until today to open it for that reason. :)

> Also, is it possible to have smaller example files?

I was wondering if I should simplify the anaphora files. Is that better?

**Comment by sushain97** [comment]
This looks much better, yep.

**Comment by mr-martian** [comment]
@sushain97 It looks like the packaging issue has been dealt with, could you rerun the tests?

**Pull request merged**
