### PR TITLE
compress files using zlib

### LINKED ISSUE #57: Compress encoded files
Could easily be a GCI task

### PR DESCRIPTION
**Pull request by mr-martian**
Closes #57, I think

### CODE REVIEW

**Comment by sushain97** [comment]
What's up with the broken build?

**Comment by mr-martian** [comment]
The error message Travis reports is
```
The command "wget http://apertium.projectjj.com/apt/install-nightly.sh -O - | sudo bash" failed and exited with 255 during .
```

**Comment by unhammer** [comment]
compress what files? (could you be a bit more specific in the git commit?)

**Comment by mr-martian** [comment]
This pr adds the step in the ```updateBootstrapper.py``` scripts of compressing the data files before encoding them and writing them to ```apertium-init.py``` which brings the file size down from 240KB to less than 80KB.

**Comment by sushain97** [comment]
The primary motivation isn't really to compress the file since any self-respecting server will gzip anyway. It's more to make the built file less annoying in some IDEs, especially since there are plugins/UI features that don't work too well with long lines. Really not a big deal but nice to have since the built file also has source code that gets edited sometimes.

**Comment by mr-martian** [comment]
My editor was definitely much happier after the change. :)

**Pull request merged**
