### PR TITLE
Update READMEs for GitHub, i.e. Markdown (fixes #33)

### LINKED ISSUE #33: Update README
The readme should be updated to remove references to SVN. There should be a symlink to README.md. The README should be made markdowny.

### PR DESCRIPTION
**Pull request by sushain97**

### CODE REVIEW

**Comment by sushain97** [comment]
@xavivars @ftyers @jonorthwash these READMEs will probably make their way into lots of modules and not be changed for a while so it would be good if any changes could be made now before I merge and release this :)

**Comment by sushain97** [comment]
Also, I'd like to change "ChangeLog" to "CHANGELOG". Thoughts? BTW, this will be a minor version bump to v2.1.0 (currently on v2.0.3).

**Comment by ftyers** [comment]
Why change ChangeLog to CHANGELOG? `ChangeLog` is GNU style[1]

1. https://www.gnu.org/prep/standards/html_node/Change-Log-Concepts.html#Change-Log-Concepts

**Comment by sushain97** [comment]
> Why change ChangeLog to CHANGELOG? ChangeLog is GNU style

This makes me really sad but very well. The inconsistency with NEWS, README, AUTHORS, COPYING is grating.

> Also, @sushain97 when you made the README changes did you look at the READMEs for pairs that I had already changed manually?

I looked at one edited by Xavi but didn't go traipsing through all of them. There were some improvements I made to that one. Feel free to push to this branch with changes to mine or just link me to the README that has improvements I should apply here.

**Comment by ftyers** [comment]
@sushain97 `incubator/apertium-udm-kpv`

**Pull request merged**
